from ..message import Message
from ..ainode import AiNode
from ..tree import TreeNode
from ..services.ux.cli_ux_service import CLIService
import json
import os
from ..execution_context import ExecutionContext
from ..services.logging.logging_service import LoggingService
from ..services.data.data_service import DataService

class ChainplateWorkflow:
    def __init__(self, xml_string: str, mode: str = "workflow",execution_id: int = None):
        json_str = TreeNode.get_xml_as_json_string(xml_string)
        data = json.loads(json_str)
        self.tree = AiNode.from_dict(data,context=ExecutionContext(execution_id=execution_id))
        self.mode = mode
        self.execution_id = execution_id

    def run(self, message: Message, ux_service=CLIService()) -> Message: # Default to the CLI for I/O

        # TODO: return object with this info so caller can decide what to do.
        # Run and display logs:
        ux_service.show_output_to_user('')

        message = self.tree.execute(message)
        final_output = message.get_payload()
        
        if self.mode == "workflow": #TODO - move this to a constant or enum for modes
            if final_output:
                ux_service.show_output_to_user('\n[WORKFLOW] >> ' + final_output)
            else:
                ux_service.show_output_to_user('[WORKFLOW] >> Warning(!) - no output generated by workflow.')
        
        ux_service.show_output_to_user('')
        message.print_logs() #TODO - pass in the FileService
        return message